apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: mongov3
  namespace: tools
spec:
  license:
    accept: true
    license: L-QECF-MBXVLU
    use: CloudPakForIntegrationProduction
  replicas: 1
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  version: '12.0'
  barURL:
    - >-
      https://raw.githubusercontent.com/leocvidal/BIANdemo/main/xml2json.bar
  configurations:
    - mongodbloopbackdatasource
    - mongodbsetdbparms
    - github-barauth